# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c5c7f7880030854afa9a0796f199b83225f75fa9eb78cf6be566f7529427b80ac74e62b3b7a950cd6b5725ef16278efdf7765545fc6b41601c4c4d3349d82fa

test:
  secret_key_base: 34858489a5b3c3437d8fc43c5e51a6e88854a17f5ed26192f6e6065a681cdbedd633c54ecc20544843354acee51f4ee632d16e932269187d3fb59ed3fc0f654b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
